import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.navbar}>
        <div className="container">
          <nav className={styles.mainnav}>
            <ul>
              <li><a href="#">Home</a></li>
              <li><a href="#">About</a></li>
              <li><a href="#">Blogs</a></li>
              <li><a href="#">contact</a></li>              
            </ul>
          </nav>
        </div>
      </div>
      <main className={styles.mainblog}>
        <div className={styles.blogswrap}>
          <div className={styles.blogheading}>
            <h1> My First Blog Page</h1>
            <p>This is the file control system on next js

            </p>
          </div>
        </div>
        <div className={styles.blogcontent}>
          <h2>Popular Blog</h2>
          <div className={styles.blogItem}>
            <h3>Next.js 13.3</h3>
            <p>Next.js 13.3 adds popular community-requested features and is the last release before the App Router is stable, including:</p>
          </div>
          <div className={styles.blogItem}>
            <h3>Next.js 13.3</h3>
            <p>Next.js 13.3 adds popular community-requested features and is the last release before the App Router is stable, including:</p>
          </div>
          <div className={styles.blogItem}>
            <h3>Next.js 13.3</h3>
            <p>Next.js 13.3 adds popular community-requested features and is the last release before the App Router is stable, including:</p>
          </div>
          <div className={styles.blogItem}>
            <h3>Next.js 13.3</h3>
            <p>Next.js 13.3 adds popular community-requested features and is the last release before the App Router is stable, including:</p>
          </div>
          <div className={styles.blogItem}>
            <h3>Next.js 13.3</h3>
            <p>Next.js 13.3 adds popular community-requested features and is the last release before the App Router is stable, including:</p>
          </div>
          <div className={styles.blogItem}>
            <h3>Next.js 13.3</h3>
            <p>Next.js 13.3 adds popular community-requested features and is the last release before the App Router is stable, including:</p>
          </div>
        </div>
      </main>
    </>
  );
}
